"""Add routine tracking

Revision ID: bc5c504077b9
Revises: 04ca2a55a11d
Create Date: 2026-05-22 16:09:50.942523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5c504077b9'
down_revision: Union[str, None] = '04ca2a55a11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_completion_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_of_day_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_completion_logs_task_id'), 'task_completion_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_completion_logs_user_id'), 'task_completion_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_completion_logs_user_id'), table_name='task_completion_logs')
    op.drop_index(op.f('ix_task_completion_logs_task_id'), table_name='task_completion_logs')
    op.drop_table('task_completion_logs')
    # ### end Alembic commands ###
